# Generated by Django 4.1.1 on 2022-12-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteModel',
            new_name='SiteInfoModel',
        ),
    ]
