# Generated by Django 4.1.1 on 2022-12-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_rename_sitemodel_siteinfomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfomodel',
            name='title',
        ),
    ]
