# Generated by Django 4.1.1 on 2022-12-22 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_remove_siteinfomodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteheromodel',
            old_name='internal_url',
            new_name='url',
        ),
    ]
