# Generated by Django 4.1.1 on 2022-12-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_rename_internal_url_siteheromodel_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAboutInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intro_description', models.TextField()),
                ('main_description', models.TextField()),
                ('founder_name', models.CharField(max_length=100)),
                ('main_image', models.FileField(upload_to='images/about')),
                ('other_image', models.FileField(upload_to='images/about')),
            ],
        ),
        migrations.AlterField(
            model_name='siteheromodel',
            name='url',
            field=models.CharField(blank=True, choices=[('about', 'ABOUT'), ('donate', 'DONATE')], max_length=50, null=True),
        ),
    ]
