# Generated by Django 3.2.12 on 2023-03-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0008_gallerymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='causemodel',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
